version: '2'
services:
  redis:
    image: redis:3.2.11
    volumes:
      - ./tmp/docker/redis/data:/data
  app:
    build: ./kubeletter/
    volumes:
      - ./kubeletter:/code
    command: lein run
    env_file:
      - .env
    depends_on:
      - redis
    ports:
      - "3000:3000"
